#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "🧠 Memory hogs (%)" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	2) setsid -f st -e htop ;;
	3) notify-send "🧠 Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs.
- Middle click to open htop." ;;
	6) st -e nvim "$0" ;;
esac

echo "$(free -h | awk '/^Mem:/ {print $3}')"
#|🔁$(free -h | awk '/^Swap:/ {print $3}')"
