#!/bin/sh

# Popup to upgrade system

printf "Beginning upgrade.\\n"

# Update and send a signal to the update displayer module afterwards
# Check for Arch Repo updates
sudo pacman -Syu; setsid -f sb-popcheck
# Check for AUR updates
yay -Syua; pkill -RTMIN+1 "${STATUSBAR:-dwmblocks}"

printf "\\nUpgrade complete.\\nPress <Enter> to exit window.\\n\\n"
read -r _
