#!/bin/sh

# Displays number of upgradeable packages.
# For this to work, have a `yay -Sy` command run in the background as a
# cronjob every so often as root. This script will then read those packages.
# When clicked, it will run an upgrade via pacman.
#
# Add the following text as a file in /usr/share/libalpm/hooks/statusbar.hook:
#
# [Trigger]
# Operation = Upgrade
# Type = Package
# Target = *
#
# [Action]
# Description = Updating statusbar...
# When = PostTransaction
# Exec = /usr/bin/pkill -RTMIN+1 dwmblocks # Or i3blocks if using i3.

case $BLOCK_BUTTON in
	1) setsid -f st -e sb-popupgrade ;;
	2) notify-send "$(/usr/bin/yay -Qu)" ;;
	3) notify-send "🎁 Upgrade module" "📦: number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
	6) st -e nvim "$0" ;;
esac

/usr/bin/yay -Qu | wc -l
