#!/bin/sh

# Displays number of upgradable packages.

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e sb-popupgrade ;;
	2) notify-send "$(checkupdates; yay -Qua)" ;;
	3) notify-send "🎁 Upgrade module" "📦: number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
	7) setsid -f "$TERMINAL" -e sudo -A -E "$EDITOR" /etc/pacman.conf ;;
esac

cat /tmp/sysupdates 2>/dev/null
