#!/bin/sh

# A dmenu prompt to enter a Brave Search query

url="https://search.brave.com/search?q="

# Searching with the engine.
query=$(:|dmenu -p 'Enter Brave query:') || exit

query="$(echo "${query}" | jq -s -R -r @uri)"
# Display search results in web browser
$BROWSER "${url}${query}"
