#!/bin/sh

# Search for a process to kill.

    selected="$(ps --user "$USER" -F | \
                dmenu -1 -l 14 -o 1 -p "Search for process to kill:" "$@" | \
                awk '{print $2" "$11}')";

    if [ -n "$selected" ]; then
        answer="$(printf "No\nYes" | dmenu -p "Kill $selected?" "$@")"

        if [ "$answer" = "Yes" ]; then
            kill -9 "${selected%% *}"
            notify-send "Process $selected has been killed." && exit 0
        else
            exit 1
#            echo "Program terminated." && exit 1
        fi
    fi
