#!/bin/sh

# xinitrc runs automatically when you run startx.

lidwatcher &		   # Lock screen/suspend when lid is closed
bgchanger &	           # Automatic background changing script
sxhkd -m 1 -r /dev/null &  # X hotkey daemon
picom &			   # Compositor
dunst &			   # Notification manager
xautolock -detectsleep &   # Autolock program (see Xresources)
unclutter --start-hidden & # Hide the mouse cursor when idle
clipmenud &		   # Clipboard manager for dmenu
xinput disable "SynPS/2 Synaptics TouchPad" &	# Disable the touchpad
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$! # Use Xresources settings

# Ensure that xrdb has finished running before starting dwm
[ -n "$xrdbpid" ] && wait "$xrdbpid"

# Start dwm
exec dwm
