#!/usr/bin/env bash
#

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing. Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

brave_search_browser="firefox-nightly"
url="https://search.brave.com/search?q="

main() {
  # shellcheck disable=SC2154

  # Searching with the engine.
  query=$(echo "$url" | dmenu -p 'Enter Brave query:')

  query="$(echo "${query}" | jq -s -R -r @uri)"
  # Display search results in web browser
  # shellcheck disable=SC2154
  ${brave_search_browser} "${url}${query}"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
