#!/usr/bin/env bash
#
# Description: Search for a process to kill.
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts

selected="$(ps --user "$(id -u)" -F | \
            dmenu -l 20 -g 1 -p "Search for process to kill:" | \
            awk '{print $2" "$11}')";

if [[ -n $selected ]]; then

    answer="$(echo -e "Yes\nNo" | dmenu -i -l 20 -p "Kill $selected?")"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
		echo "Process $selected has been killed." && exit 1
    fi

    if [[ $answer == "No" ]]; then
		echo "Program terminated." && exit 1
    fi
fi

exit 0
