#!/usr/bin/env bash
#
# Description: Search various search engines (inspired by surfraw).

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

websearch_browser="firefox"

declare -A websearch
# Syntax:
# websearch[name]="https://www.example.com/search?q="

# Search Engines
#websearch[searx]="https://searx.info/search?q="
#websearch[searx]="https://sx.fedi.tech/searx/search?q="
websearch[searx]="https://searx.fmac.xyz/search?q="
websearch[bing]="https://www.bing.com/search?q="
websearch[qwant]="https://www.qwant.com/?q="
websearch[brave search]="https://search.brave.com/search?q="
websearch[brave images]="https://search.brave.com/images?q="
websearch[startpage]="https://www.startpage.com/do/dsearch?query="
websearch[duckduckgo]="https://duckduckgo.com/?q="
websearch[google]="https://www.google.com/search?q="
websearch[google images]="https://www.google.com/search?hl=en&tbm=isch&q="
# Linux & Development
websearch[archaur]="https://aur.archlinux.org/packages/?O=0&K="
websearch[archpkg]="https://archlinux.org/packages/?sort=&q="
websearch[archwiki]="https://wiki.archlinux.org/index.php?search="
websearch[github]="https://github.com/search?q="
websearch[gitlab]="https://gitlab.com/search?search="
# Social Media
websearch[odysee]="https://odysee.com/$/search?q="
websearch[invidious]="https://invidious.kavin.rocks/search?q="
websearch[invidious video]="https://invidious.kavin.rocks/watch?v="
websearch[reddit]="https://www.reddit.com/search/?q="
websearch[youtube]="https://www.youtube.com/results?search_query="
websearch[youtube video]="https://www.youtube.com/watch?v="
websearch[piped]="https://piped.kavin.rocks/results?search_query="
websearch[piped video]="https://piped.kavin.rocks/watch?v="
# Information
websearch[urban]="https://www.urbandictionary.com/define.php?term="
websearch[webster]="https://www.merriam-webster.com/dictionary/"
websearch[thesaurus]="https://www.thesaurus.com/misspelling?term="
websearch[wikiless]="https://wikiless.org/w/index.php?search="
websearch[wikipedia]="https://wikipedia.org/w/index.php?search="
websearch[wiktionary]="https://en.wiktionary.org/w/index.php?search="
websearch[rtenews]="https://www.rte.ie/search/query/"
websearch[translate]="https://translate.google.com/?sl=auto&tl=en&text="
# Etc.
websearch[zlibrary]="https://1lib.org/s/"
websearch[soundcloud]="https://soundcloud.com/search?q="
websearch[wayback]="https://web.archive.org/web/*/"
websearch[rutracker]="https://rutracker.org/forum/tracker.php?nm="
websearch[steamgriddb]="https://www.steamgriddb.com/search/grids?term="

main() {
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154 # Choosing  a search engine by name from array above.
  engine=$(printf '%s\n' "${!websearch[@]}" | sort | dmenu -c -i -bw 3 -g 2 -l 18 -p 'Choose engine:') "$@" || exit

  # Getting the URL of the search engine we chose.
  url="${websearch["${engine}"]}"

  # Searching the chosen engine.
  query=$(echo "$engine" | dmenu -p 'Enter search query:')

  query="$(echo "${query}" | jq -s -R -r @uri)"
  # Display search results in web browser
  # shellcheck disable=SC2154
  ${websearch_browser} "${url}${query}"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
