#!/usr/bin/env bash
#
# Description: Search various search engines (inspired by surfraw).

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing. Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

searx_browser="firefox-nightly"
url="https://searx.fmac.xyz/search?q="

main() {
  # shellcheck disable=SC2154

  # Searching with the engine.
  query=$(echo "$url" | dmenu -p 'Enter SearX query:')

  query="$(echo "${query}" | jq -s -R -r @uri)"
  # Display search results in web browser
  # shellcheck disable=SC2154
  ${searx_browser} "${url}${query}"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
