#!/usr/bin/env bash
#

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail


# Defining our web browser.
website_browser="firefox"

declare -A website
# torrent sites
#website[1337x]="https://1337x.to/"
website[rutracker]="https://rutracker.org"
website[cs.rin.ru]="https://cs.rin.ru"
# google
website[google classroom]="https://classroom.google.com/u/0/h"
website[google drive]="https://drive.google.com"
website[google docs]="https://docs.google.com"
website[google photos]="https://photos.google.com"
website[google photos]="https://photos.google.com"
website[gmail]="https://gmail.com"
#
website[openweathermap]="https://openweathermap.org/city/2966485"
website[piped]="https://piped.kavin.rocks/feed"
website[lichess]="https://lichess.org"
website[protonmail]="https://mail.protonmail.com/"
website[archwiki]="https://wiki.archlinux.org/"
website[awz3converter]="https://ebook.online-convert.com/convert-to-azw3"
website[discord]="https://discord.com/app"
website[element]="https://app.element.io"
website[github]="https://github.com/"
website[gitlab]="https://gitlab.com/"
website[netflix]="https://netflix.com"
website[imgflip]="https://imgflip.com/memegenerator"
website[invidious]="https://invidious.kavin.rocks/"
website[zlibrary]="https://z-lib.org/"
website[itsfoss]="https://itsfoss.com"
website[reddit]="https://www.reddit.com/"
website[rtenews]="https://www.rte.ie/news/"
#website[searx]="https://searx.info"
#website[searx]="https://sx.fedi.tech/"
website[searx]="https://searx.fmac.xyz"
website[brave search]="https://search.brave.com"
website[soundcloud]="https://soundcloud.com/"
website[translate]="https://translate.google.com/"
website[tutanota]="https://mail.tutanota.com/"
website[wayback]="https://web.archive.org/web/"
website[webster]="https://www.merriam-webster.com/dictionary/"
website[whatsapp]="https://web.whatsapp.com"
website[wikiless]="https://wikiless.org/"
website[wikipedia]="https://wikipedia.org/"
website[wiktionary]="https://en.wiktionary.org/wiki/"
website[youtube]="https://www.youtube.com/"
##################################################################


main() {
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154 # Choosing a website by name from array above.
  engine=$(printf '%s\n' "${!website[@]}" | sort | dmenu -i -c -bw 3 -g 2 -l 18 -p 'Choose website:') "$@" || exit

  # Getting the URL of the search engine we chose.
  url="${website["${engine}"]}"

  # Display website in web browser
  # shellcheck disable=SC2154
  ${website_browser} "${url}"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
