#!/usr/bin/env bash
#
# script name: dm-wifi
# Description: Connect to wifi using dmenu
# Dependencies: dmenu, nmcli, Any Nerd Font
# Contributor: WitherCubes

set -euo pipefail

main() {
  # TODO: Fix cut line at some point
  bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -i -l 100 -p "Select Wifi  :" | cut -d' ' -f1)
  pass=$(echo "" | dmenu -i -p "Enter Password  :")
  # We are disabling a shellcheck warning about using && and || as it doesn't apply here.
  # shellcheck disable=SC2015
  [ -n "$pass" ] && nmcli device wifi connect "$bssid" password "$pass" || nmcli device wifi connect "$bssid"
  sleep 10
  if ping -q -c 2 -W 2 google.com >/dev/null; then
    notify-send "Your internet is working :)"
  else
    notify-send "Your internet is not working :("
  fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
