#!/bin/sh

# xinitrc runs automatically when you run startx.

picom &			   # Compositor
dunst &			   # Notification manager
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$! # Use Xresources settings

# Ensure that xrdb has finished running before starting dwm
[ -n "$xrdbpid" ] && wait "$xrdbpid"

# Start dwm
exec dwm
